### ISSUE TITLE
favorites.create  URL路径错误

### ISSUE THREAD

**Issue by anlong2008** [FanfouAPI/FanFouAPIDoc#52]
https://github.com/FanfouAPI/FanFouAPIDoc/wiki/favorites.create
这个页面中 路径应该是：
http://api.fanfou.com/favorites/create/:id.[json|xml|rss]

多了/statuses

请修改

**Comment by riophae** [comment]
啊哈，不知道这里还有人维护吗？

**Comment by anlong2008** [comment]
应该没有人维护了

**Comment by riophae** [comment]
请问楼主是打算做一个 iOS 的饭否 app 吗？

**Comment by zhuangya** [comment]
文档倒是可以修正一下
但是 api 的代码的确没有人维护了。
我验证一下就来修改 :)

**Comment by zhuangya** [comment]
文档已经修正了，连同 [favorites.destroy](https://github.com/FanfouAPI/FanFouAPIDoc/wiki/favorites.destroy)

**Comment by anlong2008** [comment]
我正在做iOS版本的客户端，快上线了 :-)

**Comment by zhuangya** [comment]
awesome!
